[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/solmate/lib/ds-test/src/',
    'solmate/=lib/solmate/src/',
    'ds-test/=lib/ds-test/src/',
]

## set only when the `hardhat` profile is selected
[hardhat]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]

# See more config options https://github.com/gakonst/foundry/tree/master/config